services:
  client:
    build: ./client
    ports:
     - "8000:8000"
    networks:
      - notion
  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - notion
    environment:
      NOTION_TOKEN: 
      NOTION_DATABASE_ID:  

networks:
  notion: